/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PoliceDepartment = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const Totals = IDL.Record({
  'messageCount' : IDL.Nat,
  'incidentCount' : IDL.Nat,
  'evidenceCount' : IDL.Nat,
});
export const Pattern = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'details' : IDL.Text,
});
export const ToneIntensity = IDL.Variant({
  'calm' : IDL.Null,
  'firm' : IDL.Null,
  'veryHarsh' : IDL.Null,
  'severe' : IDL.Null,
});
export const SeverityPattern = IDL.Record({
  'incidentCount' : IDL.Nat,
  'evidenceCount' : IDL.Nat,
  'intensity' : ToneIntensity,
});
export const LocationPattern = IDL.Record({
  'count' : IDL.Nat,
  'severity' : IDL.Text,
  'location' : IDL.Text,
});
export const PatternAnalysis = IDL.Record({
  'patterns' : IDL.Vec(Pattern),
  'severityPatterns' : IDL.Vec(SeverityPattern),
  'locations' : IDL.Vec(LocationPattern),
});
export const MessageTone = IDL.Variant({
  'documentationNotice' : IDL.Null,
  'formalEvidence' : IDL.Null,
  'directWarning' : IDL.Null,
});
export const IncidentMessageSummary = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'incidentId' : IDL.Text,
  'tone' : MessageTone,
  'incidentTimestamp' : IDL.Int,
  'location' : IDL.Text,
  'intensity' : IDL.Opt(ToneIntensity),
});
export const EvidenceMeta = IDL.Record({
  'id' : IDL.Nat,
  'originalFilename' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'storageId' : IDL.Text,
  'uploadTimestamp' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});
export const IncidentSummaryItem = IDL.Record({
  'id' : IDL.Text,
  'messages' : IDL.Vec(IncidentMessageSummary),
  'description' : IDL.Text,
  'evidence' : IDL.Vec(EvidenceMeta),
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
});
export const IncidentSummary = IDL.Record({
  'totalAnalysis' : Totals,
  'patternAnalysis' : PatternAnalysis,
  'messageHistory' : IDL.Vec(IncidentMessageSummary),
  'timelineItems' : IDL.Vec(IncidentSummaryItem),
});
export const GeneratedMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'incidentId' : IDL.Text,
  'tone' : MessageTone,
  'timestamp' : IDL.Int,
  'intensity' : IDL.Opt(ToneIntensity),
});
export const IncidentReport = IDL.Record({
  'id' : IDL.Text,
  'additionalNotes' : IDL.Text,
  'criminalActivityReportNumber' : IDL.Text,
  'evidenceNotes' : IDL.Text,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
  'incidentDate' : IDL.Int,
});
export const StalkerProfile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'vehicleDescription' : IDL.Opt(IDL.Text),
  'vehiclePlate' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'zipCode' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'socialMediaLinks' : IDL.Opt(IDL.Text),
  'suspectDescription' : IDL.Opt(IDL.Text),
  'fullAddress' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PlaceCandidate = IDL.Record({
  'displayName' : IDL.Text,
  'websiteUri' : IDL.Text,
  'nationalPhoneNumber' : IDL.Text,
  'rating' : IDL.Text,
  'formattedAddress' : IDL.Text,
  'telephone' : IDL.Text,
});
export const AddressPlaceCandidate = IDL.Record({
  'formattedAddress' : IDL.Text,
  'placeCandidates' : IDL.Vec(PlaceCandidate),
});
export const VictimProfile = IDL.Record({
  'dob' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const PoliceSubmissionLog = IDL.Record({
  'victimInfo' : IDL.Opt(VictimProfile),
  'attachedEvidence' : IDL.Vec(EvidenceMeta),
  'includedSummary' : IDL.Bool,
  'submissionResult' : IDL.Text,
  'narrative' : IDL.Text,
  'timestamp' : IDL.Int,
  'victimInfoIncluded' : IDL.Bool,
  'department' : PoliceDepartment,
});
export const SmsLog = IDL.Record({
  'messageContent' : IDL.Text,
  'incidentId' : IDL.Text,
  'messageId' : IDL.Nat,
  'recipient' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'confirmation' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSelectedDepartment' : IDL.Func([], [], []),
  'deletePoliceDepartment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStalkerProfile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'findNearestPoliceDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PoliceDepartment)],
      [],
    ),
  'generateIncidentSummary' : IDL.Func([], [IncidentSummary], ['query']),
  'generateMessage' : IDL.Func(
      [IDL.Text, MessageTone, IDL.Opt(ToneIntensity)],
      [GeneratedMessage],
      [],
    ),
  'getAllIncidents' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
  'getAllPoliceDepartments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PoliceDepartment))],
      ['query'],
    ),
  'getAllStalkerProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, StalkerProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvidenceForIncident' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EvidenceMeta)],
      ['query'],
    ),
  'getIncident' : IDL.Func([IDL.Text], [IDL.Opt(IncidentReport)], ['query']),
  'getMessagesForIncident' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GeneratedMessage)],
      ['query'],
    ),
  'getMotivationalVideoAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'getMotivationalVideoStorageId' : IDL.Func([], [IDL.Text], ['query']),
  'getNearestAddresses' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AddressPlaceCandidate)],
      ['query'],
    ),
  'getNearestPoliceDepartmentsToAddress' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PlaceCandidate)],
      ['query'],
    ),
  'getPoliceSubmissionLogs' : IDL.Func(
      [],
      [IDL.Vec(PoliceSubmissionLog)],
      ['query'],
    ),
  'getSelectedDepartment' : IDL.Func(
      [],
      [IDL.Opt(PoliceDepartment)],
      ['query'],
    ),
  'getSmsLogs' : IDL.Func([], [IDL.Vec(SmsLog)], ['query']),
  'getStalkerProfile' : IDL.Func([], [IDL.Opt(StalkerProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVictimProfile' : IDL.Func([], [IDL.Opt(VictimProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logPoliceSubmission' : IDL.Func(
      [
        PoliceDepartment,
        IDL.Text,
        IDL.Vec(EvidenceMeta),
        IDL.Bool,
        IDL.Opt(VictimProfile),
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
  'logSmsUsage' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveIncident' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IncidentReport],
      [],
    ),
  'saveMultipleStalkerProfile' : IDL.Func([StalkerProfile], [IDL.Nat], []),
  'savePoliceDepartment' : IDL.Func([PoliceDepartment], [IDL.Nat], []),
  'saveSelectedDepartment' : IDL.Func([PoliceDepartment], [], []),
  'saveStalkerProfile' : IDL.Func([StalkerProfile], [], []),
  'saveVictimProfile' : IDL.Func([VictimProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePoliceDepartment' : IDL.Func(
      [IDL.Nat, PoliceDepartment],
      [IDL.Bool],
      [],
    ),
  'updateStalkerProfile' : IDL.Func([IDL.Nat, StalkerProfile], [IDL.Bool], []),
  'uploadEvidence' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [EvidenceMeta],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PoliceDepartment = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const Totals = IDL.Record({
    'messageCount' : IDL.Nat,
    'incidentCount' : IDL.Nat,
    'evidenceCount' : IDL.Nat,
  });
  const Pattern = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'details' : IDL.Text,
  });
  const ToneIntensity = IDL.Variant({
    'calm' : IDL.Null,
    'firm' : IDL.Null,
    'veryHarsh' : IDL.Null,
    'severe' : IDL.Null,
  });
  const SeverityPattern = IDL.Record({
    'incidentCount' : IDL.Nat,
    'evidenceCount' : IDL.Nat,
    'intensity' : ToneIntensity,
  });
  const LocationPattern = IDL.Record({
    'count' : IDL.Nat,
    'severity' : IDL.Text,
    'location' : IDL.Text,
  });
  const PatternAnalysis = IDL.Record({
    'patterns' : IDL.Vec(Pattern),
    'severityPatterns' : IDL.Vec(SeverityPattern),
    'locations' : IDL.Vec(LocationPattern),
  });
  const MessageTone = IDL.Variant({
    'documentationNotice' : IDL.Null,
    'formalEvidence' : IDL.Null,
    'directWarning' : IDL.Null,
  });
  const IncidentMessageSummary = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'incidentId' : IDL.Text,
    'tone' : MessageTone,
    'incidentTimestamp' : IDL.Int,
    'location' : IDL.Text,
    'intensity' : IDL.Opt(ToneIntensity),
  });
  const EvidenceMeta = IDL.Record({
    'id' : IDL.Nat,
    'originalFilename' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'storageId' : IDL.Text,
    'uploadTimestamp' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  const IncidentSummaryItem = IDL.Record({
    'id' : IDL.Text,
    'messages' : IDL.Vec(IncidentMessageSummary),
    'description' : IDL.Text,
    'evidence' : IDL.Vec(EvidenceMeta),
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
  });
  const IncidentSummary = IDL.Record({
    'totalAnalysis' : Totals,
    'patternAnalysis' : PatternAnalysis,
    'messageHistory' : IDL.Vec(IncidentMessageSummary),
    'timelineItems' : IDL.Vec(IncidentSummaryItem),
  });
  const GeneratedMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'incidentId' : IDL.Text,
    'tone' : MessageTone,
    'timestamp' : IDL.Int,
    'intensity' : IDL.Opt(ToneIntensity),
  });
  const IncidentReport = IDL.Record({
    'id' : IDL.Text,
    'additionalNotes' : IDL.Text,
    'criminalActivityReportNumber' : IDL.Text,
    'evidenceNotes' : IDL.Text,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
    'incidentDate' : IDL.Int,
  });
  const StalkerProfile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'vehicleDescription' : IDL.Opt(IDL.Text),
    'vehiclePlate' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'zipCode' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'socialMediaLinks' : IDL.Opt(IDL.Text),
    'suspectDescription' : IDL.Opt(IDL.Text),
    'fullAddress' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PlaceCandidate = IDL.Record({
    'displayName' : IDL.Text,
    'websiteUri' : IDL.Text,
    'nationalPhoneNumber' : IDL.Text,
    'rating' : IDL.Text,
    'formattedAddress' : IDL.Text,
    'telephone' : IDL.Text,
  });
  const AddressPlaceCandidate = IDL.Record({
    'formattedAddress' : IDL.Text,
    'placeCandidates' : IDL.Vec(PlaceCandidate),
  });
  const VictimProfile = IDL.Record({
    'dob' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const PoliceSubmissionLog = IDL.Record({
    'victimInfo' : IDL.Opt(VictimProfile),
    'attachedEvidence' : IDL.Vec(EvidenceMeta),
    'includedSummary' : IDL.Bool,
    'submissionResult' : IDL.Text,
    'narrative' : IDL.Text,
    'timestamp' : IDL.Int,
    'victimInfoIncluded' : IDL.Bool,
    'department' : PoliceDepartment,
  });
  const SmsLog = IDL.Record({
    'messageContent' : IDL.Text,
    'incidentId' : IDL.Text,
    'messageId' : IDL.Nat,
    'recipient' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'confirmation' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSelectedDepartment' : IDL.Func([], [], []),
    'deletePoliceDepartment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStalkerProfile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'findNearestPoliceDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PoliceDepartment)],
        [],
      ),
    'generateIncidentSummary' : IDL.Func([], [IncidentSummary], ['query']),
    'generateMessage' : IDL.Func(
        [IDL.Text, MessageTone, IDL.Opt(ToneIntensity)],
        [GeneratedMessage],
        [],
      ),
    'getAllIncidents' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
    'getAllPoliceDepartments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PoliceDepartment))],
        ['query'],
      ),
    'getAllStalkerProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, StalkerProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvidenceForIncident' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EvidenceMeta)],
        ['query'],
      ),
    'getIncident' : IDL.Func([IDL.Text], [IDL.Opt(IncidentReport)], ['query']),
    'getMessagesForIncident' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GeneratedMessage)],
        ['query'],
      ),
    'getMotivationalVideoAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'getMotivationalVideoStorageId' : IDL.Func([], [IDL.Text], ['query']),
    'getNearestAddresses' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AddressPlaceCandidate)],
        ['query'],
      ),
    'getNearestPoliceDepartmentsToAddress' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlaceCandidate)],
        ['query'],
      ),
    'getPoliceSubmissionLogs' : IDL.Func(
        [],
        [IDL.Vec(PoliceSubmissionLog)],
        ['query'],
      ),
    'getSelectedDepartment' : IDL.Func(
        [],
        [IDL.Opt(PoliceDepartment)],
        ['query'],
      ),
    'getSmsLogs' : IDL.Func([], [IDL.Vec(SmsLog)], ['query']),
    'getStalkerProfile' : IDL.Func([], [IDL.Opt(StalkerProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVictimProfile' : IDL.Func([], [IDL.Opt(VictimProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logPoliceSubmission' : IDL.Func(
        [
          PoliceDepartment,
          IDL.Text,
          IDL.Vec(EvidenceMeta),
          IDL.Bool,
          IDL.Opt(VictimProfile),
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
    'logSmsUsage' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveIncident' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IncidentReport],
        [],
      ),
    'saveMultipleStalkerProfile' : IDL.Func([StalkerProfile], [IDL.Nat], []),
    'savePoliceDepartment' : IDL.Func([PoliceDepartment], [IDL.Nat], []),
    'saveSelectedDepartment' : IDL.Func([PoliceDepartment], [], []),
    'saveStalkerProfile' : IDL.Func([StalkerProfile], [], []),
    'saveVictimProfile' : IDL.Func([VictimProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePoliceDepartment' : IDL.Func(
        [IDL.Nat, PoliceDepartment],
        [IDL.Bool],
        [],
      ),
    'updateStalkerProfile' : IDL.Func(
        [IDL.Nat, StalkerProfile],
        [IDL.Bool],
        [],
      ),
    'uploadEvidence' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [EvidenceMeta],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };