/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddressPlaceCandidate {
  'formattedAddress' : string,
  'placeCandidates' : Array<PlaceCandidate>,
}
export interface DVJournal {
  'entries' : Array<JournalEntry>,
  'abuserName' : string,
}
export interface DVJournalAnalysis {
  'riskFactor' : RiskFactor,
  'analyzedTimestamp' : bigint,
  'summary' : string,
  'analyzedBy' : string,
  'suggestedActions' : Array<string>,
}
export interface EvidenceMeta {
  'id' : bigint,
  'originalFilename' : string,
  'fileSize' : bigint,
  'fileType' : string,
  'storageId' : string,
  'uploadTimestamp' : bigint,
  'uploadedBy' : Principal,
}
export interface GeneratedMessage {
  'id' : bigint,
  'content' : string,
  'incidentId' : string,
  'tone' : MessageTone,
  'timestamp' : bigint,
  'intensity' : [] | [ToneIntensity],
}
export interface HighRiskKeyword {
  'description' : string,
  'keyword' : string,
  'exampleContext' : string,
}
export interface IncidentMessageSummary {
  'id' : bigint,
  'content' : string,
  'incidentId' : string,
  'tone' : MessageTone,
  'incidentTimestamp' : bigint,
  'location' : string,
  'intensity' : [] | [ToneIntensity],
}
export interface IncidentReport {
  'id' : string,
  'additionalNotes' : string,
  'criminalActivityReportNumber' : string,
  'evidenceNotes' : string,
  'user' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'location' : string,
  'incidentDate' : bigint,
}
export interface IncidentSummary {
  'totalAnalysis' : Totals,
  'patternAnalysis' : PatternAnalysis,
  'messageHistory' : Array<IncidentMessageSummary>,
  'timelineItems' : Array<IncidentSummaryItem>,
}
export interface IncidentSummaryItem {
  'id' : string,
  'messages' : Array<IncidentMessageSummary>,
  'description' : string,
  'evidence' : Array<EvidenceMeta>,
  'timestamp' : bigint,
  'location' : string,
}
export interface JournalEntry {
  'entry' : string,
  'timestamp' : bigint,
  'timestampMs' : bigint,
}
export interface LocationPattern {
  'count' : bigint,
  'severity' : string,
  'location' : string,
}
export type MessageTone = { 'documentationNotice' : null } |
  { 'formalEvidence' : null } |
  { 'directWarning' : null };
export interface Pattern {
  'name' : string,
  'description' : string,
  'details' : string,
}
export interface PatternAnalysis {
  'patterns' : Array<Pattern>,
  'severityPatterns' : Array<SeverityPattern>,
  'locations' : Array<LocationPattern>,
}
export interface PlaceCandidate {
  'displayName' : string,
  'websiteUri' : string,
  'nationalPhoneNumber' : string,
  'rating' : string,
  'formattedAddress' : string,
  'telephone' : string,
}
export interface PoliceDepartment {
  'city' : string,
  'name' : string,
  'zipCode' : string,
  'state' : string,
  'address' : string,
  'contactNumber' : string,
}
export interface PoliceSubmissionLog {
  'victimInfo' : [] | [VictimProfile],
  'attachedEvidence' : Array<EvidenceMeta>,
  'includedSummary' : boolean,
  'submissionResult' : string,
  'narrative' : string,
  'timestamp' : bigint,
  'victimInfoIncluded' : boolean,
  'department' : PoliceDepartment,
}
export type RiskFactor = { 'low' : null } |
  { 'high' : null } |
  { 'extreme' : null } |
  { 'moderate' : null };
export interface SeverityPattern {
  'incidentCount' : bigint,
  'evidenceCount' : bigint,
  'intensity' : ToneIntensity,
}
export interface SmsLog {
  'messageContent' : string,
  'incidentId' : string,
  'messageId' : bigint,
  'recipient' : [] | [string],
  'timestamp' : bigint,
  'confirmation' : boolean,
}
export interface StalkerProfile {
  'age' : [] | [bigint],
  'vehicleDescription' : [] | [string],
  'vehiclePlate' : [] | [string],
  'city' : [] | [string],
  'name' : string,
  'zipCode' : [] | [string],
  'state' : [] | [string],
  'socialMediaLinks' : [] | [string],
  'suspectDescription' : [] | [string],
  'fullAddress' : [] | [string],
  'phoneNumber' : [] | [string],
}
export type ToneIntensity = { 'calm' : null } |
  { 'firm' : null } |
  { 'veryHarsh' : null } |
  { 'severe' : null };
export interface Totals {
  'messageCount' : bigint,
  'incidentCount' : bigint,
  'evidenceCount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VictimProfile {
  'dob' : [] | [string],
  'name' : [] | [string],
  'email' : [] | [string],
  'address' : [] | [string],
  'phoneNumber' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJournalEntry' : ActorMethod<[string], boolean>,
  'analyzeJournal' : ActorMethod<[], [] | [DVJournalAnalysis]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearSelectedDepartment' : ActorMethod<[], undefined>,
  'deletePoliceDepartment' : ActorMethod<[bigint], boolean>,
  'deleteStalkerProfile' : ActorMethod<[bigint], boolean>,
  'findNearestPoliceDepartment' : ActorMethod<
    [string],
    [] | [PoliceDepartment]
  >,
  'generateIncidentSummary' : ActorMethod<[], IncidentSummary>,
  'generateMessage' : ActorMethod<
    [string, MessageTone, [] | [ToneIntensity]],
    GeneratedMessage
  >,
  'getAbuserName' : ActorMethod<[], string>,
  'getAllIncidents' : ActorMethod<[], Array<IncidentReport>>,
  'getAllPoliceDepartments' : ActorMethod<
    [],
    Array<[bigint, PoliceDepartment]>
  >,
  'getAllStalkerProfiles' : ActorMethod<[], Array<[bigint, StalkerProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvidenceForIncident' : ActorMethod<[string], Array<EvidenceMeta>>,
  'getHighRiskKeywords' : ActorMethod<[], Array<HighRiskKeyword>>,
  'getIncident' : ActorMethod<[string], [] | [IncidentReport]>,
  'getJournal' : ActorMethod<[], [] | [DVJournal]>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getLastJournalAnalysis' : ActorMethod<[], [] | [DVJournalAnalysis]>,
  'getMessagesForIncident' : ActorMethod<[string], Array<GeneratedMessage>>,
  'getMotivationalVideoAccess' : ActorMethod<[], boolean>,
  'getMotivationalVideoStorageId' : ActorMethod<[], string>,
  'getNearestAddresses' : ActorMethod<[string], Array<AddressPlaceCandidate>>,
  'getNearestPoliceDepartmentsToAddress' : ActorMethod<
    [string],
    Array<PlaceCandidate>
  >,
  'getPoliceSubmissionLogs' : ActorMethod<[], Array<PoliceSubmissionLog>>,
  'getSelectedDepartment' : ActorMethod<[], [] | [PoliceDepartment]>,
  'getSmsLogs' : ActorMethod<[], Array<SmsLog>>,
  'getStalkerProfile' : ActorMethod<[], [] | [StalkerProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVictimProfile' : ActorMethod<[], [] | [VictimProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logPoliceSubmission' : ActorMethod<
    [
      PoliceDepartment,
      string,
      Array<EvidenceMeta>,
      boolean,
      [] | [VictimProfile],
      boolean,
      string,
    ],
    undefined
  >,
  'logSmsUsage' : ActorMethod<
    [string, bigint, string, [] | [string]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveIncident' : ActorMethod<
    [string, string, string, string],
    IncidentReport
  >,
  'saveMultipleStalkerProfile' : ActorMethod<[StalkerProfile], bigint>,
  'savePoliceDepartment' : ActorMethod<[PoliceDepartment], bigint>,
  'saveSelectedDepartment' : ActorMethod<[PoliceDepartment], undefined>,
  'saveStalkerProfile' : ActorMethod<[StalkerProfile], undefined>,
  'saveVictimProfile' : ActorMethod<[VictimProfile], undefined>,
  'setAbuserName' : ActorMethod<[string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePoliceDepartment' : ActorMethod<[bigint, PoliceDepartment], boolean>,
  'updateStalkerProfile' : ActorMethod<[bigint, StalkerProfile], boolean>,
  'uploadEvidence' : ActorMethod<
    [string, string, string, string, bigint],
    EvidenceMeta
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];