/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SeverityPattern {
    incidentCount: bigint;
    evidenceCount: bigint;
    intensity: ToneIntensity;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DVJournal {
    entries: Array<JournalEntry>;
    abuserName: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VictimProfile {
    dob?: string;
    name?: string;
    email?: string;
    address?: string;
    phoneNumber?: string;
}
export interface IncidentReport {
    id: string;
    additionalNotes: string;
    criminalActivityReportNumber: string;
    evidenceNotes: string;
    user: Principal;
    description: string;
    timestamp: bigint;
    location: string;
    incidentDate: bigint;
}
export interface Pattern {
    name: string;
    description: string;
    details: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AddressPlaceCandidate {
    formattedAddress: string;
    placeCandidates: Array<PlaceCandidate>;
}
export interface StalkerProfile {
    age?: bigint;
    vehicleDescription?: string;
    vehiclePlate?: string;
    city?: string;
    name: string;
    zipCode?: string;
    state?: string;
    socialMediaLinks?: string;
    suspectDescription?: string;
    fullAddress?: string;
    phoneNumber?: string;
}
export interface GeneratedMessage {
    id: bigint;
    content: string;
    incidentId: string;
    tone: MessageTone;
    timestamp: bigint;
    intensity?: ToneIntensity;
}
export interface IncidentMessageSummary {
    id: bigint;
    content: string;
    incidentId: string;
    tone: MessageTone;
    incidentTimestamp: bigint;
    location: string;
    intensity?: ToneIntensity;
}
export interface DVJournalAnalysis {
    riskFactor: RiskFactor;
    analyzedTimestamp: bigint;
    summary: string;
    analyzedBy: string;
    suggestedActions: Array<string>;
}
export interface HighRiskKeyword {
    description: string;
    keyword: string;
    exampleContext: string;
}
export interface SmsLog {
    messageContent: string;
    incidentId: string;
    messageId: bigint;
    recipient?: string;
    timestamp: bigint;
    confirmation: boolean;
}
export interface EvidenceMeta {
    id: bigint;
    originalFilename: string;
    fileSize: bigint;
    fileType: string;
    storageId: string;
    uploadTimestamp: bigint;
    uploadedBy: Principal;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface IncidentSummary {
    totalAnalysis: Totals;
    patternAnalysis: PatternAnalysis;
    messageHistory: Array<IncidentMessageSummary>;
    timelineItems: Array<IncidentSummaryItem>;
}
export interface PatternAnalysis {
    patterns: Array<Pattern>;
    severityPatterns: Array<SeverityPattern>;
    locations: Array<LocationPattern>;
}
export interface JournalEntry {
    entry: string;
    timestamp: bigint;
    timestampMs: bigint;
}
export interface PlaceCandidate {
    displayName: string;
    websiteUri: string;
    nationalPhoneNumber: string;
    rating: string;
    formattedAddress: string;
    telephone: string;
}
export interface Totals {
    messageCount: bigint;
    incidentCount: bigint;
    evidenceCount: bigint;
}
export interface IncidentSummaryItem {
    id: string;
    messages: Array<IncidentMessageSummary>;
    description: string;
    evidence: Array<EvidenceMeta>;
    timestamp: bigint;
    location: string;
}
export interface PoliceSubmissionLog {
    victimInfo?: VictimProfile;
    attachedEvidence: Array<EvidenceMeta>;
    includedSummary: boolean;
    submissionResult: string;
    narrative: string;
    timestamp: bigint;
    victimInfoIncluded: boolean;
    department: PoliceDepartment;
}
export interface PoliceDepartment {
    city: string;
    name: string;
    zipCode: string;
    state: string;
    address: string;
    contactNumber: string;
}
export interface LocationPattern {
    count: bigint;
    severity: string;
    location: string;
}
export enum MessageTone {
    documentationNotice = "documentationNotice",
    formalEvidence = "formalEvidence",
    directWarning = "directWarning"
}
export enum RiskFactor {
    low = "low",
    high = "high",
    extreme = "extreme",
    moderate = "moderate"
}
export enum ToneIntensity {
    calm = "calm",
    firm = "firm",
    veryHarsh = "veryHarsh",
    severe = "severe"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addJournalEntry(entry: string): Promise<boolean>;
    analyzeJournal(): Promise<DVJournalAnalysis | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearSelectedDepartment(): Promise<void>;
    deletePoliceDepartment(deptId: bigint): Promise<boolean>;
    deleteStalkerProfile(profileId: bigint): Promise<boolean>;
    findNearestPoliceDepartment(address: string): Promise<PoliceDepartment | null>;
    generateIncidentSummary(): Promise<IncidentSummary>;
    generateMessage(incidentId: string, tone: MessageTone, intensity: ToneIntensity | null): Promise<GeneratedMessage>;
    getAbuserName(): Promise<string>;
    getAllIncidents(): Promise<Array<IncidentReport>>;
    getAllPoliceDepartments(): Promise<Array<[bigint, PoliceDepartment]>>;
    getAllStalkerProfiles(): Promise<Array<[bigint, StalkerProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEvidenceForIncident(incidentId: string): Promise<Array<EvidenceMeta>>;
    getHighRiskKeywords(): Promise<Array<HighRiskKeyword>>;
    getIncident(id: string): Promise<IncidentReport | null>;
    getJournal(): Promise<DVJournal | null>;
    getJournalEntries(): Promise<Array<JournalEntry>>;
    getLastJournalAnalysis(): Promise<DVJournalAnalysis | null>;
    getMessagesForIncident(incidentId: string): Promise<Array<GeneratedMessage>>;
    getMotivationalVideoAccess(): Promise<boolean>;
    getMotivationalVideoStorageId(): Promise<string>;
    getNearestAddresses(searchTerm: string): Promise<Array<AddressPlaceCandidate>>;
    getNearestPoliceDepartmentsToAddress(term: string): Promise<Array<PlaceCandidate>>;
    getPoliceSubmissionLogs(): Promise<Array<PoliceSubmissionLog>>;
    getSelectedDepartment(): Promise<PoliceDepartment | null>;
    getSmsLogs(): Promise<Array<SmsLog>>;
    getStalkerProfile(): Promise<StalkerProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVictimProfile(): Promise<VictimProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logPoliceSubmission(department: PoliceDepartment, submissionResult: string, attachedEvidence: Array<EvidenceMeta>, victimInfoIncluded: boolean, victimInfo: VictimProfile | null, includedSummary: boolean, narrative: string): Promise<void>;
    logSmsUsage(incidentId: string, messageId: bigint, messageContent: string, recipient: string | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveIncident(location: string, description: string, evidenceNotes: string, additionalNotes: string): Promise<IncidentReport>;
    saveMultipleStalkerProfile(profile: StalkerProfile): Promise<bigint>;
    savePoliceDepartment(department: PoliceDepartment): Promise<bigint>;
    saveSelectedDepartment(persistedDepartment: PoliceDepartment): Promise<void>;
    saveStalkerProfile(profile: StalkerProfile): Promise<void>;
    saveVictimProfile(profile: VictimProfile): Promise<void>;
    setAbuserName(abuserName: string): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePoliceDepartment(deptId: bigint, department: PoliceDepartment): Promise<boolean>;
    updateStalkerProfile(profileId: bigint, profile: StalkerProfile): Promise<boolean>;
    uploadEvidence(incidentId: string, storageId: string, originalFilename: string, fileType: string, fileSize: bigint): Promise<EvidenceMeta>;
}
import type { DVJournal as _DVJournal, DVJournalAnalysis as _DVJournalAnalysis, EvidenceMeta as _EvidenceMeta, GeneratedMessage as _GeneratedMessage, IncidentMessageSummary as _IncidentMessageSummary, IncidentReport as _IncidentReport, IncidentSummary as _IncidentSummary, IncidentSummaryItem as _IncidentSummaryItem, LocationPattern as _LocationPattern, MessageTone as _MessageTone, Pattern as _Pattern, PatternAnalysis as _PatternAnalysis, PoliceDepartment as _PoliceDepartment, PoliceSubmissionLog as _PoliceSubmissionLog, RiskFactor as _RiskFactor, SeverityPattern as _SeverityPattern, SmsLog as _SmsLog, StalkerProfile as _StalkerProfile, ToneIntensity as _ToneIntensity, Totals as _Totals, UserProfile as _UserProfile, UserRole as _UserRole, VictimProfile as _VictimProfile, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addJournalEntry(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0);
            return result;
        }
    }
    async analyzeJournal(): Promise<DVJournalAnalysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeJournal();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeJournal();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearSelectedDepartment(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSelectedDepartment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSelectedDepartment();
            return result;
        }
    }
    async deletePoliceDepartment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePoliceDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePoliceDepartment(arg0);
            return result;
        }
    }
    async deleteStalkerProfile(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStalkerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStalkerProfile(arg0);
            return result;
        }
    }
    async findNearestPoliceDepartment(arg0: string): Promise<PoliceDepartment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findNearestPoliceDepartment(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findNearestPoliceDepartment(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateIncidentSummary(): Promise<IncidentSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.generateIncidentSummary();
                return from_candid_IncidentSummary_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateIncidentSummary();
            return from_candid_IncidentSummary_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateMessage(arg0: string, arg1: MessageTone, arg2: ToneIntensity | null): Promise<GeneratedMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMessage(arg0, to_candid_MessageTone_n34(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
                return from_candid_GeneratedMessage_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMessage(arg0, to_candid_MessageTone_n34(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
            return from_candid_GeneratedMessage_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAbuserName(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAbuserName();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAbuserName();
            return result;
        }
    }
    async getAllIncidents(): Promise<Array<IncidentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncidents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncidents();
            return result;
        }
    }
    async getAllPoliceDepartments(): Promise<Array<[bigint, PoliceDepartment]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPoliceDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPoliceDepartments();
            return result;
        }
    }
    async getAllStalkerProfiles(): Promise<Array<[bigint, StalkerProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStalkerProfiles();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStalkerProfiles();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvidenceForIncident(arg0: string): Promise<Array<EvidenceMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceForIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceForIncident(arg0);
            return result;
        }
    }
    async getHighRiskKeywords(): Promise<Array<HighRiskKeyword>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHighRiskKeywords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHighRiskKeywords();
            return result;
        }
    }
    async getIncident(arg0: string): Promise<IncidentReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncident(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncident(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournal(): Promise<DVJournal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournal();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournal();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries();
            return result;
        }
    }
    async getLastJournalAnalysis(): Promise<DVJournalAnalysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastJournalAnalysis();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastJournalAnalysis();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesForIncident(arg0: string): Promise<Array<GeneratedMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesForIncident(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesForIncident(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMotivationalVideoAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getMotivationalVideoAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMotivationalVideoAccess();
            return result;
        }
    }
    async getMotivationalVideoStorageId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMotivationalVideoStorageId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMotivationalVideoStorageId();
            return result;
        }
    }
    async getNearestAddresses(arg0: string): Promise<Array<AddressPlaceCandidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearestAddresses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearestAddresses(arg0);
            return result;
        }
    }
    async getNearestPoliceDepartmentsToAddress(arg0: string): Promise<Array<PlaceCandidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearestPoliceDepartmentsToAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearestPoliceDepartmentsToAddress(arg0);
            return result;
        }
    }
    async getPoliceSubmissionLogs(): Promise<Array<PoliceSubmissionLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoliceSubmissionLogs();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoliceSubmissionLogs();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSelectedDepartment(): Promise<PoliceDepartment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSelectedDepartment();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSelectedDepartment();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmsLogs(): Promise<Array<SmsLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmsLogs();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmsLogs();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStalkerProfile(): Promise<StalkerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStalkerProfile();
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStalkerProfile();
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVictimProfile(): Promise<VictimProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVictimProfile();
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVictimProfile();
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logPoliceSubmission(arg0: PoliceDepartment, arg1: string, arg2: Array<EvidenceMeta>, arg3: boolean, arg4: VictimProfile | null, arg5: boolean, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logPoliceSubmission(arg0, arg1, arg2, arg3, to_candid_opt_n62(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logPoliceSubmission(arg0, arg1, arg2, arg3, to_candid_opt_n62(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async logSmsUsage(arg0: string, arg1: bigint, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logSmsUsage(arg0, arg1, arg2, to_candid_opt_n65(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSmsUsage(arg0, arg1, arg2, to_candid_opt_n65(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveIncident(arg0: string, arg1: string, arg2: string, arg3: string): Promise<IncidentReport> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIncident(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIncident(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveMultipleStalkerProfile(arg0: StalkerProfile): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMultipleStalkerProfile(to_candid_StalkerProfile_n66(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMultipleStalkerProfile(to_candid_StalkerProfile_n66(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async savePoliceDepartment(arg0: PoliceDepartment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.savePoliceDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePoliceDepartment(arg0);
            return result;
        }
    }
    async saveSelectedDepartment(arg0: PoliceDepartment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSelectedDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSelectedDepartment(arg0);
            return result;
        }
    }
    async saveStalkerProfile(arg0: StalkerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStalkerProfile(to_candid_StalkerProfile_n66(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStalkerProfile(to_candid_StalkerProfile_n66(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveVictimProfile(arg0: VictimProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVictimProfile(to_candid_VictimProfile_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVictimProfile(to_candid_VictimProfile_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setAbuserName(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAbuserName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAbuserName(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePoliceDepartment(arg0: bigint, arg1: PoliceDepartment): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePoliceDepartment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePoliceDepartment(arg0, arg1);
            return result;
        }
    }
    async updateStalkerProfile(arg0: bigint, arg1: StalkerProfile): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStalkerProfile(arg0, to_candid_StalkerProfile_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStalkerProfile(arg0, to_candid_StalkerProfile_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadEvidence(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<EvidenceMeta> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadEvidence(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadEvidence(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_DVJournalAnalysis_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DVJournalAnalysis): DVJournalAnalysis {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_GeneratedMessage_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneratedMessage): GeneratedMessage {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentMessageSummary_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentMessageSummary): IncidentMessageSummary {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentSummaryItem_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentSummaryItem): IncidentSummaryItem {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentSummary_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentSummary): IncidentSummary {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MessageTone_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageTone): MessageTone {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PatternAnalysis_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatternAnalysis): PatternAnalysis {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PoliceSubmissionLog_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PoliceSubmissionLog): PoliceSubmissionLog {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_RiskFactor_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskFactor): RiskFactor {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SeverityPattern_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeverityPattern): SeverityPattern {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SmsLog_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SmsLog): SmsLog {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_StalkerProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StalkerProfile): StalkerProfile {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ToneIntensity_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToneIntensity): ToneIntensity {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_VictimProfile_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VictimProfile): VictimProfile {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PoliceDepartment]): PoliceDepartment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ToneIntensity]): ToneIntensity | null {
    return value.length === 0 ? null : from_candid_ToneIntensity_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IncidentReport]): IncidentReport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DVJournal]): DVJournal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VictimProfile]): VictimProfile | null {
    return value.length === 0 ? null : from_candid_VictimProfile_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StalkerProfile]): StalkerProfile | null {
    return value.length === 0 ? null : from_candid_StalkerProfile_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DVJournalAnalysis]): DVJournalAnalysis | null {
    return value.length === 0 ? null : from_candid_DVJournalAnalysis_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    riskFactor: _RiskFactor;
    analyzedTimestamp: bigint;
    summary: string;
    analyzedBy: string;
    suggestedActions: Array<string>;
}): {
    riskFactor: RiskFactor;
    analyzedTimestamp: bigint;
    summary: string;
    analyzedBy: string;
    suggestedActions: Array<string>;
} {
    return {
        riskFactor: from_candid_RiskFactor_n11(_uploadFile, _downloadFile, value.riskFactor),
        analyzedTimestamp: value.analyzedTimestamp,
        summary: value.summary,
        analyzedBy: value.analyzedBy,
        suggestedActions: value.suggestedActions
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalAnalysis: _Totals;
    patternAnalysis: _PatternAnalysis;
    messageHistory: Array<_IncidentMessageSummary>;
    timelineItems: Array<_IncidentSummaryItem>;
}): {
    totalAnalysis: Totals;
    patternAnalysis: PatternAnalysis;
    messageHistory: Array<IncidentMessageSummary>;
    timelineItems: Array<IncidentSummaryItem>;
} {
    return {
        totalAnalysis: value.totalAnalysis,
        patternAnalysis: from_candid_PatternAnalysis_n18(_uploadFile, _downloadFile, value.patternAnalysis),
        messageHistory: from_candid_vec_n25(_uploadFile, _downloadFile, value.messageHistory),
        timelineItems: from_candid_vec_n31(_uploadFile, _downloadFile, value.timelineItems)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patterns: Array<_Pattern>;
    severityPatterns: Array<_SeverityPattern>;
    locations: Array<_LocationPattern>;
}): {
    patterns: Array<Pattern>;
    severityPatterns: Array<SeverityPattern>;
    locations: Array<LocationPattern>;
} {
    return {
        patterns: value.patterns,
        severityPatterns: from_candid_vec_n20(_uploadFile, _downloadFile, value.severityPatterns),
        locations: value.locations
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    incidentCount: bigint;
    evidenceCount: bigint;
    intensity: _ToneIntensity;
}): {
    incidentCount: bigint;
    evidenceCount: bigint;
    intensity: ToneIntensity;
} {
    return {
        incidentCount: value.incidentCount,
        evidenceCount: value.evidenceCount,
        intensity: from_candid_ToneIntensity_n23(_uploadFile, _downloadFile, value.intensity)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    incidentId: string;
    tone: _MessageTone;
    incidentTimestamp: bigint;
    location: string;
    intensity: [] | [_ToneIntensity];
}): {
    id: bigint;
    content: string;
    incidentId: string;
    tone: MessageTone;
    incidentTimestamp: bigint;
    location: string;
    intensity?: ToneIntensity;
} {
    return {
        id: value.id,
        content: value.content,
        incidentId: value.incidentId,
        tone: from_candid_MessageTone_n28(_uploadFile, _downloadFile, value.tone),
        incidentTimestamp: value.incidentTimestamp,
        location: value.location,
        intensity: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.intensity))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    messages: Array<_IncidentMessageSummary>;
    description: string;
    evidence: Array<_EvidenceMeta>;
    timestamp: bigint;
    location: string;
}): {
    id: string;
    messages: Array<IncidentMessageSummary>;
    description: string;
    evidence: Array<EvidenceMeta>;
    timestamp: bigint;
    location: string;
} {
    return {
        id: value.id,
        messages: from_candid_vec_n25(_uploadFile, _downloadFile, value.messages),
        description: value.description,
        evidence: value.evidence,
        timestamp: value.timestamp,
        location: value.location
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    incidentId: string;
    tone: _MessageTone;
    timestamp: bigint;
    intensity: [] | [_ToneIntensity];
}): {
    id: bigint;
    content: string;
    incidentId: string;
    tone: MessageTone;
    timestamp: bigint;
    intensity?: ToneIntensity;
} {
    return {
        id: value.id,
        content: value.content,
        incidentId: value.incidentId,
        tone: from_candid_MessageTone_n28(_uploadFile, _downloadFile, value.tone),
        timestamp: value.timestamp,
        intensity: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.intensity))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: [] | [bigint];
    vehicleDescription: [] | [string];
    vehiclePlate: [] | [string];
    city: [] | [string];
    name: string;
    zipCode: [] | [string];
    state: [] | [string];
    socialMediaLinks: [] | [string];
    suspectDescription: [] | [string];
    fullAddress: [] | [string];
    phoneNumber: [] | [string];
}): {
    age?: bigint;
    vehicleDescription?: string;
    vehiclePlate?: string;
    city?: string;
    name: string;
    zipCode?: string;
    state?: string;
    socialMediaLinks?: string;
    suspectDescription?: string;
    fullAddress?: string;
    phoneNumber?: string;
} {
    return {
        age: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.age)),
        vehicleDescription: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.vehicleDescription)),
        vehiclePlate: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.vehiclePlate)),
        city: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.city)),
        name: value.name,
        zipCode: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.zipCode)),
        state: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.state)),
        socialMediaLinks: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.socialMediaLinks)),
        suspectDescription: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.suspectDescription)),
        fullAddress: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.fullAddress)),
        phoneNumber: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.phoneNumber))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    victimInfo: [] | [_VictimProfile];
    attachedEvidence: Array<_EvidenceMeta>;
    includedSummary: boolean;
    submissionResult: string;
    narrative: string;
    timestamp: bigint;
    victimInfoIncluded: boolean;
    department: _PoliceDepartment;
}): {
    victimInfo?: VictimProfile;
    attachedEvidence: Array<EvidenceMeta>;
    includedSummary: boolean;
    submissionResult: string;
    narrative: string;
    timestamp: bigint;
    victimInfoIncluded: boolean;
    department: PoliceDepartment;
} {
    return {
        victimInfo: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.victimInfo)),
        attachedEvidence: value.attachedEvidence,
        includedSummary: value.includedSummary,
        submissionResult: value.submissionResult,
        narrative: value.narrative,
        timestamp: value.timestamp,
        victimInfoIncluded: value.victimInfoIncluded,
        department: value.department
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dob: [] | [string];
    name: [] | [string];
    email: [] | [string];
    address: [] | [string];
    phoneNumber: [] | [string];
}): {
    dob?: string;
    name?: string;
    email?: string;
    address?: string;
    phoneNumber?: string;
} {
    return {
        dob: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.dob)),
        name: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.name)),
        email: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.email)),
        address: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.address)),
        phoneNumber: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.phoneNumber))
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messageContent: string;
    incidentId: string;
    messageId: bigint;
    recipient: [] | [string];
    timestamp: bigint;
    confirmation: boolean;
}): {
    messageContent: string;
    incidentId: string;
    messageId: bigint;
    recipient?: string;
    timestamp: bigint;
    confirmation: boolean;
} {
    return {
        messageContent: value.messageContent,
        incidentId: value.incidentId,
        messageId: value.messageId,
        recipient: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.recipient)),
        timestamp: value.timestamp,
        confirmation: value.confirmation
    };
}
function from_candid_tuple_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _StalkerProfile]): [bigint, StalkerProfile] {
    return [
        value[0],
        from_candid_StalkerProfile_n43(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    extreme: null;
} | {
    moderate: null;
}): RiskFactor {
    return "low" in value ? RiskFactor.low : "high" in value ? RiskFactor.high : "extreme" in value ? RiskFactor.extreme : "moderate" in value ? RiskFactor.moderate : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    calm: null;
} | {
    firm: null;
} | {
    veryHarsh: null;
} | {
    severe: null;
}): ToneIntensity {
    return "calm" in value ? ToneIntensity.calm : "firm" in value ? ToneIntensity.firm : "veryHarsh" in value ? ToneIntensity.veryHarsh : "severe" in value ? ToneIntensity.severe : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documentationNotice: null;
} | {
    formalEvidence: null;
} | {
    directWarning: null;
}): MessageTone {
    return "documentationNotice" in value ? MessageTone.documentationNotice : "formalEvidence" in value ? MessageTone.formalEvidence : "directWarning" in value ? MessageTone.directWarning : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SeverityPattern>): Array<SeverityPattern> {
    return value.map((x)=>from_candid_SeverityPattern_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncidentMessageSummary>): Array<IncidentMessageSummary> {
    return value.map((x)=>from_candid_IncidentMessageSummary_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncidentSummaryItem>): Array<IncidentSummaryItem> {
    return value.map((x)=>from_candid_IncidentSummaryItem_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _StalkerProfile]>): Array<[bigint, StalkerProfile]> {
    return value.map((x)=>from_candid_tuple_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GeneratedMessage>): Array<GeneratedMessage> {
    return value.map((x)=>from_candid_GeneratedMessage_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PoliceSubmissionLog>): Array<PoliceSubmissionLog> {
    return value.map((x)=>from_candid_PoliceSubmissionLog_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SmsLog>): Array<SmsLog> {
    return value.map((x)=>from_candid_SmsLog_n59(_uploadFile, _downloadFile, x));
}
function to_candid_MessageTone_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageTone): _MessageTone {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_StalkerProfile_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StalkerProfile): _StalkerProfile {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_ToneIntensity_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToneIntensity): _ToneIntensity {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_VictimProfile_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VictimProfile): _VictimProfile {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToneIntensity | null): [] | [_ToneIntensity] {
    return value === null ? candid_none() : candid_some(to_candid_ToneIntensity_n37(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VictimProfile | null): [] | [_VictimProfile] {
    return value === null ? candid_none() : candid_some(to_candid_VictimProfile_n63(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dob?: string;
    name?: string;
    email?: string;
    address?: string;
    phoneNumber?: string;
}): {
    dob: [] | [string];
    name: [] | [string];
    email: [] | [string];
    address: [] | [string];
    phoneNumber: [] | [string];
} {
    return {
        dob: value.dob ? candid_some(value.dob) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none()
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    vehicleDescription?: string;
    vehiclePlate?: string;
    city?: string;
    name: string;
    zipCode?: string;
    state?: string;
    socialMediaLinks?: string;
    suspectDescription?: string;
    fullAddress?: string;
    phoneNumber?: string;
}): {
    age: [] | [bigint];
    vehicleDescription: [] | [string];
    vehiclePlate: [] | [string];
    city: [] | [string];
    name: string;
    zipCode: [] | [string];
    state: [] | [string];
    socialMediaLinks: [] | [string];
    suspectDescription: [] | [string];
    fullAddress: [] | [string];
    phoneNumber: [] | [string];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        vehicleDescription: value.vehicleDescription ? candid_some(value.vehicleDescription) : candid_none(),
        vehiclePlate: value.vehiclePlate ? candid_some(value.vehiclePlate) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        name: value.name,
        zipCode: value.zipCode ? candid_some(value.zipCode) : candid_none(),
        state: value.state ? candid_some(value.state) : candid_none(),
        socialMediaLinks: value.socialMediaLinks ? candid_some(value.socialMediaLinks) : candid_none(),
        suspectDescription: value.suspectDescription ? candid_some(value.suspectDescription) : candid_none(),
        fullAddress: value.fullAddress ? candid_some(value.fullAddress) : candid_none(),
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageTone): {
    documentationNotice: null;
} | {
    formalEvidence: null;
} | {
    directWarning: null;
} {
    return value == MessageTone.documentationNotice ? {
        documentationNotice: null
    } : value == MessageTone.formalEvidence ? {
        formalEvidence: null
    } : value == MessageTone.directWarning ? {
        directWarning: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToneIntensity): {
    calm: null;
} | {
    firm: null;
} | {
    veryHarsh: null;
} | {
    severe: null;
} {
    return value == ToneIntensity.calm ? {
        calm: null
    } : value == ToneIntensity.firm ? {
        firm: null
    } : value == ToneIntensity.veryHarsh ? {
        veryHarsh: null
    } : value == ToneIntensity.severe ? {
        severe: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
